### PR TITLE
Cleanup, seems to work again with modern pry

### PR DESCRIPTION
**Pull request by steakknife**
**Note:** Friendly competition that hasn't happened (yet?) https://github.com/pry/pry-stack_explorer/issues/23

(It would be nice if RubyGems specs supported n-levels of forking credit/s.)

### CODE REVIEW

**Comment by epitron** [comment]
Thanks, steaky! :trophy:

**Comment by steakknife** [comment]
:metal:

**Comment by epitron** [comment]
I did some refactorings! :hand:

**Comment by steakknife** [comment]
Looks mostly good, apart from unconventional `.gemspec`.  GJ.

**Pull request merged**
