### PR TITLE
Refactor^2

### PR DESCRIPTION
**Pull request by steakknife**
For maybe even more :metal: 

(Queue dueling :violin: :notes:)

:)

### CODE REVIEW

**Comment by steakknife** [comment]
Might want to enable Travis in this repo's settings and throw the build status badge in the readme.

**Comment by steakknife** [comment]
Extra what?

**Comment by steakknife** [comment]
The most important thing: what you released sadly doesn't work.  Did you even test it?

**Comment by epitron** [comment]
It doesn't work for you? That's odd. It's working for me. A few of the tests were failing though. I'll look into it.

**Comment by epitron** [comment]
BTW, I hope you didn't get offended at my replies to your commits -- I wasn't trying to dismiss them. I was just busy, and I couldn't really comment very clearly since I was doing it from my phone.

**Pull request merged**
